name: openstack
base: core22
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  snap-openstack aims to provide a scalable, simple to deploy OpenStack solution.
version: "2024.1"

confinement: strict
grade: stable

architectures:
  - build-on: amd64

system-usernames:
  snap_daemon: shared

layout:
  /usr/share/terraform/plugins:
    symlink: $SNAP_DATA/terraform-plugins

apps:
  openstack:
    command: bin/openstack
    completer: usr/share/bash-completion/completions/openstack
    plugs:
      - network
      - home
      - dot-config-openstack
      - etc-openstack
      - ssh-public-keys
  clusterd:
    command: commands/clusterd.start
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network
      - network-bind
  sunbeam:
    command: bin/sunbeam
    plugs:
      - dot-local-share-juju
      - home
      - network
      - network-bind
      - ssh-keys
      - dot-config-openstack
      - etc-openstack
      - dot-local-share-openstack
    environment:
      PATH: $PATH:$SNAP/juju/bin
  terraform:
    command: bin/terraform
    plugs:
      - home
      - network
      - ssh-public-keys
      - juju-client-observe
    environment:
      PATH: $PATH:$SNAP/juju/bin

parts:
  dqlite:
    build-attributes: [core22-step-dependencies]
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - libsqlite3-0
    build-packages:
      - libuv1-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  sunbeam-cluster:
    after:
      - dqlite
    plugin: go
    source: ./sunbeam-microcluster
    source-type: local
    build-snaps:
      - go/1.22/stable
    build-environment:
      - GOFLAGS: -mod=readonly -ldflags=-s
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${SNAPCRAFT_STAGE}/include/ -I${SNAPCRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${SNAPCRAFT_STAGE}/lib/ -L${SNAPCRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)|(-s)"

      # Build the binaries
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/sunbeamd" -tags=libsqlite3 ./cmd/sunbeamd
    prime:
      - bin/sunbeamd

  terraform:
    plugin: go
    source: https://github.com/hashicorp/terraform
    source-depth: 1
    source-type: git
    source-tag: "v1.3.7"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp terraform $SNAPCRAFT_PART_INSTALL/bin/terraform
    stage:
      - bin/terraform

  terraform-sunbeam-plans:
    after: [terraform]
    plugin: dump
    source: cloud/
    override-build: |
      craftctl default
      for plan in $(ls $SNAPCRAFT_PART_INSTALL/etc/);
      do
        cd $SNAPCRAFT_PART_INSTALL/etc/$plan
        $SNAPCRAFT_STAGE/bin/terraform init
        $SNAPCRAFT_STAGE/bin/terraform providers mirror $SNAPCRAFT_PRIME/usr/share/terraform-providers
        rm -rf ./.terraform
      done

  terraform-openstack-plan:
    after: [terraform]
    plugin: dump
    source: https://github.com/canonical/sunbeam-terraform
    source-depth: 1
    source-type: git
    source-branch: stable/2023.2
    organize:
      '*': etc/deploy-openstack/
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL
      $SNAPCRAFT_STAGE/bin/terraform init
      $SNAPCRAFT_STAGE/bin/terraform providers mirror $SNAPCRAFT_PRIME/usr/share/terraform-providers
      rm -rf $SNAPCRAFT_PART_INSTALL/.terraform

  wrappers:
    plugin: dump
    source: snap-wrappers/

  manifests:
    plugin: dump
    source: manifests/
    organize:
      '*': etc/manifests/

  sunbeam-and-openstackclients:
    plugin: python
    source: .
    source-subdir: sunbeam-python/
    python-packages:
      - aodhclient
      - osc-placement
      - python-barbicanclient
      - python-cloudkittyclient
      - python-congressclient
      - python-designateclient
      - python-freezerclient
      - python-glanceclient
      - python-heatclient
      - python-ironicclient
      - python-keystoneclient
      - python-magnumclient
      - python-manilaclient
      - python-masakariclient
      - python-mistralclient
      - python-monascaclient
      - python-muranoclient
      - python-saharaclient
      - python-senlinclient
      - python-swiftclient
      - python-tackerclient
      - python-troveclient
      - python-vitrageclient
      - python-watcherclient
      - python-zaqarclient
      - python-neutronclient
      - python-openstackclient
      - gnocchiclient
      - python-octaviaclient
      - setuptools_scm
      - toml
      - setuptools-rust
      - Cython
    python-constraints:
      - upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - gcc
      - cython3
      - rustc
      - cargo
    override-prime: |
      craftctl default
      # Write out snap hooks
      snap-helpers write-hooks
      # This is the last step, let's now compile all our pyc files.
      ./bin/python3 -m compileall .
      # Generate completer script snippets
      mkdir -p usr/share/bash-completion/completions
      ./bin/openstack complete > usr/share/bash-completion/completions/openstack
      echo "complete -F _openstack openstack.openstack" >> usr/share/bash-completion/completions/openstack

  plugin-packages:
    plugin: nil
    stage-packages:
      - git
    stage:
      - -usr/share/doc

plugs:
  juju-bin:
    interface: content
    content: juju
    target: $SNAP/juju

  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju

  dot-local-share-openstack:
    interface: personal-files
    write:
      - $HOME/.local/share/openstack

  dot-config-openstack:
    interface: personal-files
    write:
    - $HOME/.config/openstack

  etc-openstack:
    interface: system-files
    read:
    - /etc/openstack
